version: '3'
services:
  web:
    build:
      context: .
      target: dev
    tty: true
    command: npm run start:dev
    volumes:
      - .:/src
      - /src/node_modules
    ports:
      - "80:8080"
    environment:
      NODE_ENV: development